[Variables]
fontface=Fira Code
ProcessInterval=5
lightColor1=98,148,161,255
lightColor2=98,148,161,150
darkColor1=56,79,85,200
darkColor2=56,79,85,136
darkColor3=51,127,58,100
whiteColor=255,255,255,255
Scanlines=         

;Menu Items

Item1Text=Brave Browser
Item1Target="C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe"
Item1Desc=Internet web browser
Item2Text=Developer
Item2Target=D:\Developer
Item2Desc=User music collection
Item3Text=Downloads
Item3Target=C:\Users\guine\Downloads
Item3Desc=Common internet downloads folder
Item4Text=Documents
Item4Target=C:\Users\guine\OneDrive\Documentos
Item5Desc=User documents
Item5Text=Terminal
Item5Target=wt.exe
Item5Desc=Windows Terminal Preview
Item6Text=Intellij Idea
Item6Target=C:\Program Files\JetBrains\IntelliJ IDEA 2020.3.4\bin\idea64.exe
Item6Desc=Java Code Editor
Item7Text=Obsidian
Item7Target=C:\Users\guine\AppData\Local\Obsidian\Obsidian.exe
Item7Desc=Note-taking App
Item9Text=Postman
Item9Target=C:\Users\guine\AppData\Local\Postman\Postman.exe
Item9Desc=API Client
Item8Text=Spotify
Item8Target=spotify.exe
Item8Desc=Late-capitalism music provider
Item10Text=Trash
Item10Target=shell:RecycleBinFolder
Item10Desc=Recycle bin
