
[Variables]

;--- IMPORTANT
; -- Please go to https://www.whatismybrowser.com/detect/what-is-my-user-agent
;-   Then copy the User Agent and paste it below.

MyUserAgent = Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0

; --- # CurrencyPair URLs #  ---
; find the three-letter codes for the currencies you want to display 
;  and enter them below.

PairName1=USD / BRL
CurrencyPair1=FOREX_USDBRL

PairName2=EUR / BRL
CurrencyPair2=FOREX_EURBRL

PairName3=CAD / BRL
CurrencyPair3=FOREX_CADBRL

PairName4=Euro / CAD 
CurrencyPair4=FOREX_CADEUR

PairName5=BTC / USD
CurrencyPair5=CRYPTO_BTCUSD

PairName6=ETH / USD
CurrencyPair6=CRYPTO_ETHUSD



;---------------------------------





