[Variables]

; --- PROGRESS BAR
orientation_progressbar=Vertical
width_progressbar=1.1
height_progressbar=55
xpos_progressbar=48.4
ypos_progressbar=6.6

; --- NOW
xpos_now=44
ypos_now=24.2

; --- PLAYING
xpos_playing=44
ypos_playing=31.9

; --- NOW PLAYING FOR CENTER
xpos_nowplaying=151.8
ypos_nowplaying=9.9

; --- UPDATE INDICATOR
xpos_indicator=15.4
ypos_indicator=25.85

; --- TIME
xpos_time=44
ypos_time=7.7

; --- PROGRESS
xpos_progress=44
ypos_progress=14.3

; --- SETTINGS
xpos_settings=27.5
ypos_settings=14.3

; --- PLAY BUTTON
xpos_play=26.4
ypos_play=51.7

; --- PREVIOUS BUTTON
xpos_prev=44
ypos_prev=44

; --- NEXT BUTTON
xpos_next=44
ypos_next=51.7

; --- INTERFACE
align_interface=Right

; --- REGULAR: CONTAINERS
xpos_container_reg=53.9
ypos_containertop_reg=12.1
ypos_containerbtm_reg=31.35
width_container_reg=239.25

; --- STANDARD: CONTAINERS
width_container_std=239.25
width_container_scroll=281.6
height_container_std=24.2

; --- CONTAINER TEXT
xpos_containertext=0
ypos_containertextbtm=0
ypos_containertexttop=26.4
align_containertext_supposed=Left

; PURE --------------

; --- PURE, UPDATE INDICATOR
pure_xpos_indicator=0

; --- PURE, REGULAR: CONTAINERS
pure_ypos_containertop_reg=9.9
pure_ypos_containerbtm_reg=29.15
