;//////////////////////////////////////////////////////////////////////////////////////////////////
;                                 Network Meter Default Settings
;//////////////////////////////////////////////////////////////////////////////////////////////////

[Variables]
dColorFontTitle=255,255,255
dColorFontSubtitle=144,238,144
dColorInfoText1=107,198,250
ddColorInfoText2=201,205,209
dColorFontLine=255,246,42
dColorFontLineDay=255,255,255
dColorShineStartTime=52,250,72
dColorFontLinePastTime=164,164,164
dColorShineBase=255,255,255
dColorFontSubtitle1=92,211,247
dColorFontSubtitle2=255,255,255
dColorNotFound=255,50,30
dLat=-8.096330
dLong=-34.916380
dAlt=11
dTimeZone=GMT
dCity=Recife
dLanguage=English
ddLinkPosConfig="http://www.heavens-above.com/main.aspx?lat=51.4826&lng=0&loc=Greenwich&alt=11&tz=GMT"