;//////////////////////////////////////////////////////////////////////////////////////////////////
;                                     ISS Meter Settings
;//////////////////////////////////////////////////////////////////////////////////////////////////

[Variables]
; background
BgAlpha=10
BgStyle=2
Language=English
LinkPosSettings=http://www.heavens-above.com/main.aspx?lat=51.4826&lng=0&loc=Greenwich&alt=11&tz=GMTend

; bar graph position
BarPosX=82
; font appearance
ColorFontTitle=121,203,217
ColorFontSubtitle=0,255,255
ColorInfoText1=107,198,250
ColorInfoText2=201,205,209
ColorFontLine=153,153,153
ColorFontLineDay=102,102,102
ColorShineStartTime=52,250,72
ColorFontLinePastTime=164,164,164
ColorShineBase=255,255,255
ColorFontSubtitle1=238,238,238
ColorFontSubtitle2=162,255,0
ColorNotFound=255,50,30
FontName=Fira Code
FontSize1=7
FontSize2=8
FontSizeS=5
Lat=51.482578
Long=-34.916382
Alt=0
TimeZone=GMT
City=Recife
Linkbase="http://www.heavens-above.com/"
LinkPosConfig=#Linkbase#SelectLocation.aspx?lat=-8.096330&lng=-34.916380&loc=Recife&alt=11&tz=GMT
lien="#Linkbase#PassSummary.aspx?satid=25544&lat=#Lat#&lng=#Long#&loc=#City#&alt=#Alt#&tz=#TimeZone#"
urls="\IssCard\ISSCard.ini"
; scale factor
Scale=0.955

; text position
TextPosX=8


