


[Variables]


BubbleLink1=https://www.reddit.com/
BubbleLink2=chrome.exe
BubbleLink3=WINWORD.EXE
BubbleLink4=C:\Program Files (x86)\Steam\Steam.exe
BubbleLink5=https://www.youtube.com/
BubbleLink6=C:\Users\99villages\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Spotify
BubbleLink7=https://www.facebook.com/
BubbleLink8=C:\ProgramData\Microsoft\Windows\Start Menu\Programs\TeamSpeak 3 Client
BubbleLink9=http://gmail.com/
BubbleLink10=C:\Program Files (x86)\Minecraft\MinecraftLauncher.exe

BubbleIcon1=#@#Images\BubbleLauncher\\Reddit.png
BubbleIcon2=#@#Images\BubbleLauncher\Chrome.png
BubbleIcon3=#@#Images\BubbleLauncher\MSWord.png
BubbleIcon4=#@#Images\BubbleLauncher\steam.png
BubbleIcon5=#@#Images\BubbleLauncher\youtube.png
BubbleIcon6=#@#Images\BubbleLauncher\spotify.png
BubbleIcon7=#@#Images\BubbleLauncher\face.png
BubbleIcon8=#@#Images\BubbleLauncher\teamspeak.png
BubbleIcon9=#@#Images\BubbleLauncher\Gmail.png
BubbleIcon10=#@#Images\BubbleLauncher\\MineCraft.png

Barlink1=chrome.exe
Barlink2=https://www.reddit.com/
Barlink3=http://gmail.com/
Barlink4=C:\Program Files (x86)\Steam\Steam.exe
Barlink5=https://www.facebook.com/
Barlink6=C:\Program Files (x86)\Skype\Phone\Skype.exe
Barlink7=https://www.youtube.com/

XmenLink1=http://www.gamespot.com/
XmenName1=GameSpot

XmenLink2=https://www.youtube.com/
XmenName2=YouTube

XmenLink3=https://www.ign.com
XmenName3=IGN

XmenLink4=http://deviantart.com/
XmenName4=DeviantArt


XmenLink5=https://www.facebook.com
XmenName5=FaceBook

XmenLink6=http://www.imdb.com/
XmenName6=IMDB



glowlink1=google
glowlinkPath1=www.facebook.com

glowlink2=Reddit
glowlinkPath2=www.reddit.com

glowlink3=Gmail
glowlinkPath3=https://mail.google.com/mail/

glowlink4=Deviantart
glowlinkPath4=https://www.deviantart.com/

glowlink5=YouTube
glowlinkPath5=https://www.youtube.com/

glowlink6=Facebook
glowlinkPath6=www.facebook.com
