
[Variables]

;   Replace one of the RSS Feeds below with your new link and change the name


RSS1=http://feeds.bbci.co.uk/news/rss.xml?edition=uk
RSStitle1=BBC News

RSS2=http://feeds.gawker.com/lifehacker/full
RSStitle2=Lifehacker


RSS3=http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml
RSStitle3=NewYork Times

RSS4=http://www.msn.com/rss/news.aspx
RSStitle4=MSN News

RSS5=http://news.google.com/news?pz=1&ned=us&hl=en&topic=h&num=10&output=rss
RSStitle5=Google News

RSS6=http://www.gamespot.com/rss/game_updates.php?platform=5&type=3
RSStitle6=GameSpot


Glink1=VLC.exe
Glink2=C:\Users\99villqges
Glink3=::{20D04FE0-3AEA-1069-A2D8-08002B30309D}
Glink4=::{450D8FBA-AD25-11D0-98A8-0800361B1103}
Glink5=Firefox.exe
Glink6=Photoshop.exe

Gname1=VLC
Gname2=%1
Gname3=Computer
Gname4=ff
Gname5=Firefox
Gname6=Photoshop


Ilink1=www.facebook.com
Ilink2=www.deviantart.com
Ilink3=www.reddit.com
Ilink4=C:\Program Files (x86)\Skype\Phone\Skype.exe
Ilink5=www.youtube.com
Ilink6=www.twitter.com

Iname1=FACEBOOK
Iname2=DEVIANTA.
Iname3=REDDIT
Iname4=Skype
Iname5=Youtube
Iname6=Twitter


Launcher1=www.twitter.com
Launcher2=www.facebook.com
Launcher3=www.youtube.com
Launcher4=www.reddit.com
Launcher5=chrome.exe
Launcher6=steam.exe
Launcher7=www.gmail.com
Launcher8=itunes.exe

CutA=::{450D8FBA-AD25-11D0-98A8-0800361B1103}
CutB=::{59031a47-3f72-44a7-89c5-5595fe6b30ee}
Cutc=::{645FF040-5081-101B-9F08-00AA002F954E}
CutD=::{5399E694-6CE5-4D6C-8FCE-1D8870FDCBA0}
CutE=::{374DE290-123F-4565-9164-39C4925E467B}
CutF=::{B4BFCC3A-DB2C-424C-B029-7FE99A87C641}

CutName1=FACEBOOK
CutName2=User's Profile
CutName3=Recycle Bin
CutName4=Control Panel
CutName5=Downloads
CutName6=Desktop

