
[Variables]


Latitude=-3.7304512
Longitude=-38.5217989

Units=m
Langz=en-EN


UpdateRate=600

Band3=41
GroupNumber=40

WEATHER.COM=https://weather.com/#Langz#/weather/today/l/#Latitude#,#Longitude#?temp=#Units#
GoogleMaps=https://www.google.com/maps/search/#Latitude#,#Longitude#


APIKey=21d8a80b3d6b444998a80b3d6b1449d3

CommonSubstitute='"':"","^null$":"","\\u002F":"/","\\u005C":"\","\\u003C":"<","\\u003E":">"
URLSite=https://api.weather.com/v3/aggcommon/v3-wx-observations-current;v3-wx-forecast-daily-15day;v3alertsHeadlines;v3-location-point?format=json&geocode=#Latitude#,#Longitude#&units=#Units#&language=#Langz#&apiKey=#APIKey#




LocationCode=UKXX0085


;User name without @gmail.com

UserName=99villages.manfort

Password=444virus

Zipcode=UKXX0085

CMXX0001
TimeFormat=%#H:%M

Shortcut1=C:\Windows\System32\rundll32.exe user32.dll, LockWorkStation

Shortcut2=shutdown.exe -l 

Shortcut3=shutdown.exe -h

Shortcut4=shutdown.exe -r -t 0

Shortcut5=shutdown.exe -s -t 0

InfoPic=Maria Hill

Language=English

LeftNeon=L
RightNeon=L





Tscale=f
TempScale=C
ScaleUnit=°C
Name1=Disk C
Name2=CPU
MaxTemp1=70
MaxTemp2=105
MaxGPUTemp=105
GPUNumber=0
HDDNumber=4
CoreNumber=7
HoloName1=Age
HoloAns1=??
HoloName2=Gendre
HoloAns2=Male
Identity=%1
Height=1.62
Weight=85
HeartBeats=14

Font1=Gliscor Gothic
Font2=Myriad Pro
Font3=Ebrima
Font4=Digital
Font5=Cambria
Font6=Arial
Font7=Segoe UI
Font8=Impact
Font9=BRLNSR
Font10=Alien League
Font11=The secret
Font12=Anurati

Drive1=C:
Drive2=D:
Drive3=F:
Drive4=G:


DownMax =500
UpMax =300

Flare1=0
Flare=1

WeatherIcons=#ROOTCONFIGPATH#\@Resources\Weathericons
;------------------------Time Format----------

Format="%I"
Format2="%I:%M"




Hour=I

;---


Path1=C:\Users\99villages
Path1Name=%1

Path2=::{20D04FE0-3AEA-1069-A2D8-08002B30309D}
Path2Name=Computer

Path3=::{450D8FBA-AD25-11D0-98A8-0800361B1103}
Path3Name=Documents


Path4=C:\Program Files\Adobe\Adobe Photoshop CC 2015\Photoshop.exe
path4Name=Photoshop

Path5=C:\Program Files (x86)\Mozilla Firefox\firefox.exe
Path5Name=Firefox



Llink1=www.twitter.com
Llink2=www.facebook.com
Llink3=C:\Program Files (x86)\Skype\Phone/skype.exe
Llink4=www.msn.com

Social1=#@#\Images\Leftcorner\Twitter.png
Social2=#@#\Images/Leftcorner/facebook.png
Social3=#@#\Images/Leftcorner/skype.png
Social4=#@#\Images/Leftcorner/MSN.png


Link1=C:\
Link2=::{645FF040-5081-101B-9F08-00AA002F954E}
Link3=::{20D04FE0-3AEA-1069-A2D8-08002B30309D}
Link4=D:\Program Files
Link5=::{450D8FBA-AD25-11D0-98A8-0800361B1103}


Name1A=Disk C
Name2=Trash
Name3=Computer
Name4=PES 2021
Name5=Docs

ImageTint4=0,255,255

RealPic=%USERPROFILE%\Pictures\

Hour=I


PA=ZeroGroup
PB=VisualGroup



Answer1=%1
Answer2=25
Answer3=Male
Answer4=1,8m
Answer5=Brown
Answer6=Black

NeonLightName=Images/Visualisers/Neonlights/ray
NeonLightName2=Images/Visualisers/Neonlights/ray2


NeonLightPers=Images/Perspective/p
NeonLightPers2=Images/Perspective/pr
NeonlightSurface=Images/Perspective/s
NeonLightPersLeft=Images/Perspective2/p
NeonLightPers2Left=Images/Perspective2/pr
NeonlightSurfaceLeft=Images/Perspective2/s
NeonPixa=Images/Perspective/Pixa/Pixa

NeonLightPersi=Images/Perspective/p
NeonLightPers2i=Images/Perspective/pr
NeonlightSurfacei=Images/Perspective/s
NeonLightPersLefti=Images/Perspective2/p
NeonLightPers2Lefti=Images/Perspective2/pr
NeonlightSurfaceLefti=Images/Perspective2/s
NeonPixai=Images/Perspective/Pixa/Pixa

Perspsensi=40
Perspsensi2=40
Perspsensi3=40

NeonLightsSensi=35

CloudHide=0
CloudHideA=0
Cloudcolor=0,50,255

Pcloud1=0

GlowtimeRotate=-5

Circle=Circles

MusicPlayer=Spotify
Ringon=0
Beamsensi=22
Others=0
Spotify=1

Auto=0
Manu=1

Glasstimetilt=0

pmhidden=0

xxl=1

CustomImage=C:\Users\Manfort\Documents\Rainmeter\Skins\Neon Space\@Resources\Images\Overlay\RingGlow.png
ImageHeight=400
ImageWidth=400


TimeZone=+3
SETTINGS=#CURRENTPATH#\config.exe
WEATHER.COM=http://www.weather.com/#Units#/weather/today/#LocationCode#
MoonDetailes=http://www.die.net/moon/
HELP=#@#Help.txt
MoonUpdate=3600

; How often to update the weather information. Default is 600 or 10 minutes.

UpdateRate=600

; Don't change these.

LanguagePath=/#Units#
URLcurrent=https://weather.com/#Units#/weather/today/l/#LocationCode#
URLforecast=https://weather.com/#Units#/weather/tenday/l/#LocationCode#
URLhourbyhour=https://weather.com/#Units#/weather/hourbyhour/l/#LocationCode#
